source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'angularjs-rails'
gem 'bootstrap', git: 'https://github.com/twbs/bootstrap-rubygem'
gem 'delayed_job'
gem 'delayed_job_active_record'
gem 'erb2haml'
gem 'font-awesome-rails'
gem 'haml-rails'
gem 'httparty'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-datatables-rails', '~> 3.4.0'
gem 'mysql2', '~> 0.3.18'
gem 'rails', '4.2.0'
gem 'sass-rails', '~> 5.0'
gem 'state_machine'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'byebug'
  gem 'quiet_assets'
  gem 'web-console', '~> 2.0'
end
